name: Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: stable
        override: true
    - name: Build
      run: cargo build
    - uses: katyo/publish-crates@v1
      with:
        registry-token: ${{ secrets.CARGO }}
        args: "--allow-dirty"
